### ISSUE TITLE
Repo Organization

### ISSUE THREAD

**Issue by Saydemr** [Saydemr/EPPuGNN#22]
Need to re-organize the repo to remove clutter. I think it is not necessary before the paper. But having several Readme files on folders would be great.

**Comment by burcula** [comment]
We can handle .gitignore from a central file. But we should do smth about data creation...

**Comment by Saydemr** [comment]
Need to determine which column to use as labels in the networkx graph. HS has some missing entrez gene ids and gene symbols are strings which take too much space. Having biogrid id as label requires mapping between biogrid id to entrez gene id or gene symbol...

**Comment by Saydemr** [comment]
Need to create a parameter dictionary for each organism
